export const ROLES = {
  ADMIN: "ADMIN",
  DEVELOPER: "DEVELOPER",
  TESTER: "TESTER",
  SECURITY_TEAM: "SECURITY_TEAM",
};

export const PERMISSIONS = {
  CREATE_BUG: "CREATE_BUG",
  UPDATE_BUG: "UPDATE_BUG",
  DELETE_BUG: "DELETE_BUG",
  ASSIGN_BUG: "ASSIGN_BUG",
  VIEW_BUG: "VIEW_BUG",
  ADD_COMMENT: "ADD_COMMENT",
  VIEW_AUDIT_LOGS: "VIEW_AUDIT_LOGS",
  VIEW_SECURITY_DASHBOARD: "VIEW_SECURITY_DASHBOARD",
};

const ADMIN_BUG_PERMISSIONS = [
  PERMISSIONS.CREATE_BUG,
  PERMISSIONS.UPDATE_BUG,
  PERMISSIONS.DELETE_BUG,
  PERMISSIONS.ASSIGN_BUG,
  PERMISSIONS.VIEW_BUG,
  PERMISSIONS.ADD_COMMENT,
];

/** Mirrors backend rolePermissionMap for UI gating (not authoritative — API enforces) */
export const ROLE_PERMISSION_MAP = {
  ADMIN: ADMIN_BUG_PERMISSIONS,
  DEVELOPER: [
    PERMISSIONS.CREATE_BUG,
    PERMISSIONS.UPDATE_BUG,
    PERMISSIONS.VIEW_BUG,
    PERMISSIONS.ADD_COMMENT,
  ],
  TESTER: [
    PERMISSIONS.CREATE_BUG,
    PERMISSIONS.UPDATE_BUG,
    PERMISSIONS.VIEW_BUG,
    PERMISSIONS.ADD_COMMENT,
  ],
  [ROLES.SECURITY_TEAM]: [
    PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.VIEW_SECURITY_DASHBOARD,
  ],
};
